---
# See https://github.com/jvautier/project-cli
fullname: jvautier/ansible-role-doctl
description: Install doctl client through ansible
tags:
  - ansible
  - ansible-role
  - doctl
  - digitalocean
github:
  has_issues: true
  has_projects: false
  has_wiki: false
